### ISSUE TITLE
计算偏移量时代码有误

### ISSUE THREAD

**Issue by forevercy** [SouthernBox/RippleLayout#1]
getRipplePoint 方法中有一段代码如下：
            //波峰外的偏移坐标
            if (staticX > originY) {
                targetX = staticX + offsetX;
            } else {
                targetX = staticX - offsetX;
            }
            if (staticY > originY) {
                targetY = staticY + offsetY;
            } else {
                targetY = staticY - offsetY;
            }

第一个if中的判断条件staticX > originY是不是应该改成staticX > originX，该后代码如下：
             //波峰外的偏移坐标
            if (staticX > originX) {
                targetX = staticX + offsetX;
            } else {
                targetX = staticX - offsetX;
            }
            if (staticY > originY) {
                targetY = staticY + offsetY;
            } else {
                targetY = staticY - offsetY;
            }

**Comment by NanBox** [comment]
@forevercy 已经修改，感谢指正！
